-- Camping Car Rental - Oracle Database Schema & Seed Data (Updated)

-- 1. Drop existing tables if they exist (ordered to respect dependencies)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE RENTAL CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE USERCOUPONS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE COUPONS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CAR CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE COMPANY CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE USERS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Drop new tables if exist
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE USER_COUPONS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE COUPON CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- 2. Create Sequence
CREATE SEQUENCE user_coupons_seq START WITH 1 INCREMENT BY 1;

-- 3. Create Tables

-- USERS 테이블 (회원 정보)
CREATE TABLE USERS (
    license  VARCHAR2(50) NOT NULL,
    name     VARCHAR2(50) NOT NULL,
    password VARCHAR2(255) NOT NULL,
    address  VARCHAR2(255) NOT NULL,
    phone    VARCHAR2(50) NOT NULL,
    email    VARCHAR2(100) NOT NULL,
    
    CONSTRAINT pk_users PRIMARY KEY (license)
);

-- COMPANY 테이블 (대여 회사)
CREATE TABLE COMPANY (
    companyId           NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    companyName         VARCHAR2(100) NOT NULL,
    companyAddress      VARCHAR2(255) NOT NULL,
    companyPhone        VARCHAR2(50) NULL,
    representativeName  VARCHAR2(50) NOT NULL,
    representativeEmail VARCHAR2(100) NULL,
    
    CONSTRAINT pk_company PRIMARY KEY (companyId)
);

-- CAR 테이블 (캠핑카)
CREATE TABLE CAR (
    carId          NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    companyId      NUMBER(19) NOT NULL,
    carName        VARCHAR2(100) NOT NULL,
    carNumber      VARCHAR2(50) NOT NULL,
    numberOfRider  NUMBER(10) NOT NULL,
    carImage       VARCHAR2(500) NULL,
    carDetail      VARCHAR2(1000) NULL,
    carRentalCost  NUMBER(19) NOT NULL,
    
    CONSTRAINT pk_car PRIMARY KEY (carId),
    CONSTRAINT fk_car_company FOREIGN KEY (companyId) REFERENCES COMPANY(companyId) ON DELETE CASCADE
);

-- RENTAL 테이블 (예약 이력)
CREATE TABLE RENTAL (
    rentalId      NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    carId         NUMBER(19) NOT NULL,
    username      VARCHAR2(50) NOT NULL,
    companyId     NUMBER(19) NOT NULL,
    startDateTime DATE NOT NULL,
    endDateTime   DATE NOT NULL,
    totalCost     NUMBER(19) NOT NULL,
    user_coupon_id NUMBER(19) NULL,
    
    CONSTRAINT pk_rental PRIMARY KEY (rentalId),
    CONSTRAINT fk_rental_car FOREIGN KEY (carId) REFERENCES CAR(carId) ON DELETE CASCADE,
    CONSTRAINT fk_rental_company FOREIGN KEY (companyId) REFERENCES COMPANY(companyId) ON DELETE CASCADE
);

-- COUPON 테이블 (쿠폰 마스터)
CREATE TABLE COUPON (
    coupon_id        NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    coupon_name      VARCHAR2(100) NOT NULL,
    coupon_code      VARCHAR2(50) NOT NULL,
    discount_type    VARCHAR2(20) NOT NULL, -- 'percent' or 'amount'
    discount_value   NUMBER(10) NOT NULL,
    min_order_amount NUMBER(19) DEFAULT 0 NOT NULL,
    end_date         DATE NOT NULL,
    
    CONSTRAINT pk_coupon PRIMARY KEY (coupon_id)
);

-- USER_COUPONS 테이블 (유저 발급 쿠폰)
CREATE TABLE USER_COUPONS (
    user_coupon_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    username       VARCHAR2(50) NOT NULL,
    coupon_id      NUMBER(19) NOT NULL,
    is_used        NUMBER(1) DEFAULT 0 NOT NULL,
    issued_at      DATE NOT NULL,
    used_at        DATE NULL,
    
    CONSTRAINT pk_user_coupons PRIMARY KEY (user_coupon_id),
    CONSTRAINT fk_user_coupons_coupon FOREIGN KEY (coupon_id) REFERENCES COUPON(coupon_id) ON DELETE CASCADE
);

-- 4. Insert Seed Data

-- Insert Sample Users
INSERT INTO USERS (license, name, password, address, phone, email)
VALUES ('12-34-56', 'test', 'password', 'Seoul', '010-1234-5678', 'test@test.com');

-- Insert Sample Companies
INSERT INTO COMPANY (companyName, companyAddress, companyPhone, representativeName, representativeEmail) 
VALUES ('서울 캠핑 스타', '서울특별시 강남구 테헤란로 123', '02-123-4567', '김서울', 'seoul_star@camping.com');

INSERT INTO COMPANY (companyName, companyAddress, companyPhone, representativeName, representativeEmail) 
VALUES ('메트로 캠핑 서울', '서울특별시 마포구 월드컵북로 45', '02-987-6543', '이서울', 'metro_seoul@camping.com');

INSERT INTO COMPANY (companyName, companyAddress, companyPhone, representativeName, representativeEmail) 
VALUES ('대전 한빛 캠핑카', '대전광역시 유성구 대학로 99', '042-555-1234', '박대전', 'hanbit_dj@camping.com');

INSERT INTO COMPANY (companyName, companyAddress, companyPhone, representativeName, representativeEmail) 
VALUES ('제주 바람 캠핑카', '제주특별자치도 제주시 공항로 1', '064-777-8888', '최제주', 'wind_jeju@camping.com');

INSERT INTO COMPANY (companyName, companyAddress, companyPhone, representativeName, representativeEmail) 
VALUES ('경기 숲속 캠핑', '경기도 수원시 팔달구 효원로 200', '031-222-3333', '정경기', 'forest_gg@camping.com');

INSERT INTO COMPANY (companyName, companyAddress, companyPhone, representativeName, representativeEmail) 
VALUES ('부산 바다 캠핑', '부산광역시 해운대구 해운대해변로 292', '051-888-9999', '강부산', 'sea_busan@camping.com');


-- Insert Sample Cars
-- Seoul Star Cars (Company ID 1)
INSERT INTO CAR (companyId, carName, carNumber, numberOfRider, carDetail, carRentalCost, carImage)
VALUES (1, '포레스트 프리미엄', '12가 3456', 4, 'https://images.unsplash.com/photo-1513313778780-9ae4807465f0?auto=format&fit=crop&q=80&w=600', '최신형 프리미엄 캠핑카로 넓은 실내 공간과 최고급 빌트인 가구, 풀옵션 주방 시스템 및 개별 샤워실을 완비하고 있어 4인 가족 여행에 최적화된 모델입니다.', 250000);

INSERT INTO CAR (companyId, carName, carNumber, numberOfRider, carDetail, carRentalCost, carImage)
VALUES (1, '컴팩트 마실', '34러 7890', 2, '연인들을 위한 아담하고 아늑한 2인승 캠핑카입니다. 실용적인 레이아웃과 감성적인 무드등이 탑재되어 조용하고 낭만적인 차박 여행에 안성맞춤입니다.', 150000);

-- Metro Camping Seoul Cars (Company ID 2)
INSERT INTO CAR (companyId, carName, carNumber, numberOfRider, carDetail, carRentalCost, carImage)
VALUES (2, '어반 오디세이', '56배 1357', 3, '도심 탈출을 꿈꾸는 직장인들을 위한 스타일리시한 캠핑카. 탁월한 연비와 주행 편의성을 갖추고 있으며 루프탑 텐트가 기본 장착되어 있습니다.', 180000);

-- Daejeon Hanbit Cars (Company ID 3)
INSERT INTO CAR (companyId, carName, carNumber, numberOfRider, carDetail, carRentalCost, carImage)
VALUES (3, '대전 한빛 1호', '78고 2468', 5, '5인 탑승 및 취침이 가능한 대형 모터홈입니다. 넓은 리빙룸 영역과 태양광 충전 시스템이 내장되어 있어 노지 캠핑 시 전력 걱정 없이 편리한 캠핑이 가능합니다.', 280000);

-- Jeju Wind Cars (Company ID 4)
INSERT INTO CAR (companyId, carName, carNumber, numberOfRider, carDetail, carRentalCost, carImage)
VALUES (4, '제주 바람 스테이', '90너 3579', 4, '제주도의 푸른 바다와 산바다를 만끽하기에 완벽한 오프로드 주행 가능 캠핑카입니다. 야외 테라스용 사이드 어닝과 감성 가득한 나무 인테리어가 매력적입니다.', 220000);

-- Gyeonggi Forest Cars (Company ID 5)
INSERT INTO CAR (companyId, carName, carNumber, numberOfRider, carDetail, carRentalCost, carImage)
VALUES (5, '네이처 스위트', '12오 9876', 4, '자연 친화적인 우드 톤의 럭셔리 모터홈입니다. 넓은 수납공간과 안락한 침대 매트리스가 구비되어 있어 장기 캠핑 여행을 준비하시는 가족단위 고객에게 강추합니다.', 260000);

-- Busan Sea Cars (Company ID 6)
INSERT INTO CAR (companyId, carName, carNumber, numberOfRider, carDetail, carRentalCost, carImage)
VALUES (6, '블루 오션', '34조 5432', 2, '바다가 보이는 언덕 위 차박에 완벽하게 튜닝된 미니밴 캠핑카입니다. 차량 후면 전체가 통창 느낌으로 개방되어 멋진 오션뷰를 침대에서 감상할 수 있습니다.', 160000);


-- Insert Sample Coupons
INSERT INTO COUPON (coupon_name, coupon_code, discount_type, discount_value, min_order_amount, end_date)
VALUES ('가입 환영 10% 할인쿠폰', 'WELCOME10', 'percent', 10, 0, TO_DATE('2026-12-31', 'YYYY-MM-DD'));

INSERT INTO COUPON (coupon_name, coupon_code, discount_type, discount_value, min_order_amount, end_date)
VALUES ('주말 특별 30,000원 할인쿠폰', 'WEEKEND30K', 'amount', 30000, 100000, TO_DATE('2026-12-31', 'YYYY-MM-DD'));

INSERT INTO COUPON (coupon_name, coupon_code, discount_type, discount_value, min_order_amount, end_date)
VALUES ('첫 렌트 보너스 10,000원 할인쿠폰', 'FIRST10K', 'amount', 10000, 0, TO_DATE('2026-12-31', 'YYYY-MM-DD'));

INSERT INTO COUPON (coupon_name, coupon_code, discount_type, discount_value, min_order_amount, end_date)
VALUES ('무제한 5% 할인쿠폰', 'ALWAYS5', 'percent', 5, 0, TO_DATE('2026-12-31', 'YYYY-MM-DD'));


-- Issue Coupons for 'test' User
INSERT INTO USER_COUPONS (username, coupon_id, is_used, issued_at)
VALUES ('test', 1, 0, SYSDATE);

INSERT INTO USER_COUPONS (username, coupon_id, is_used, issued_at)
VALUES ('test', 2, 0, SYSDATE);

INSERT INTO USER_COUPONS (username, coupon_id, is_used, issued_at)
VALUES ('test', 3, 0, SYSDATE);

INSERT INTO USER_COUPONS (username, coupon_id, is_used, issued_at)
VALUES ('test', 4, 0, SYSDATE);

COMMIT;
